### ISSUE TITLE
要約で`Element`が誤って翻訳されている

### ISSUE THREAD

**Issue by momdo** [masuP9/aom#7]
https://masup9.github.io/aom/spec/

>- DOM APIを使用する要素の セマンティクス を表現したり変更したりする
>- 要素間の セマンティクスの関係 を表現する
>- 要素で構成されない canvasに基づいたユーザーインターフェース 視覚的なユーザーインターフェースの セマンティクス を表現する

原文で`<code>Element</code>`となっているのはDOMのそれ（のはず）なので、翻訳しないのがただしいかと。

**Comment by masuP9** [comment]
ありがとうございます！ `Element` のママが正しいってことですね。理解。
